name: uas_mobile_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.2.6
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.0
  google_fonts: ^6.3.3
  firebase_core: ^4.3.0
  google_sign_in: ^6.2.1  
  intl: ^0.20.2
  image_picker: ^1.2.1
  firebase_messaging: ^16.1.0
  firebase_auth: ^6.1.3
  flutter_local_notifications: ^19.5.0
  image_cropper: ^11.0.0
  lottie: ^3.1.0
  alarm: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

# Konfigurasi Icon Launcher (ditaruh di root, bukan di dalam flutter)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/Note_Z.png"

# Bagian FLUTTER (Hanya boleh ada satu)
flutter:
  uses-material-design: true
  
  assets:
    # Folder Lottie (yang baru ditambahkan)
    - assets/load/
    - assets/alarm/alarm.wav

    # Gambar-gambar lainnya (yang sudah ada sebelumnya)
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/coding.jpeg
    - assets/images/membaca.jpeg
    - assets/images/menanam.jpeg
    - assets/images/reptil.jpeg
    - assets/icon/Note_Z.png
    - assets/images/global.png
    - assets/images/ramzy.png
    - assets/images/lendra.JPG
    - assets/images/ilham.png
    - assets/images/nuha.png
    - assets/screenshots/splashsreen_global.png
    - assets/screenshots/splashsreen1.png
    - assets/screenshots/splashsreen2.png
    - assets/screenshots/splashsreen3.png
    - assets/screenshots/login.png
    - assets/screenshots/login_auth.png
    - assets/screenshots/home.png
    - assets/screenshots/add_task.png
    - assets/screenshots/foreground_ntf.png
    - assets/screenshots/background_ntf.png
    - assets/screenshots/edit_task.png
    - assets/screenshots/delete_task.png
    - assets/screenshots/edit_profile.png
    - assets/screenshots/dev_team.png